### PR TITLE
Update chunking_introduction.ipynb

### PR DESCRIPTION
**Pull request by pl-marasco**
single kerchunk file doesn't require .open_mfdataset but only  .open_dateset

### CODE REVIEW

**Comment by pl-marasco** [comment]
Also added a new link to the GAUL repository

**Review by acocac — CHANGES_REQUESTED** [review]
Lorenzo,
Thanks for working on these notebooks.
The chunking notebook works fine.
The xarray handson notebook requires some work. Please check my comments through ReviewNB.

**Comment by pl-marasco** [comment]
<p>Right, as I was pointg during the discussion with the OpenEO guys it's not anymore possible to use the VITO's backend for free and credit's are now in place. Up to now I don't know other backend and I've to test other solution. </p><p>I would leave this as it is. </p><p>Morover this is not a notebook that will be used in the workshop but the purpose was only to let Michele follow the overall processing flow. </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/pangeo-openeo-BiDS-2023/pull/9/discussion/#comment-1768047689'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>that's definetly a mistake indeed. </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/pangeo-openeo-BiDS-2023/pull/9/discussion/#comment-1768047664'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>Great - It makes then sense to leave as it's. fyi, the wildfire notebook won't be used too. However, I've implemented the changes suggested by Michele.</p>

---

 <a href='https://app.reviewnb.com/pangeo-data/pangeo-openeo-BiDS-2023/pull/9/discussion/#comment-1768047689'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tinaok** [comment]
@acocac @pl-marasco can you please confirm that I can merge?

**Review by acocac — APPROVED** [review]

**Comment by acocac** [comment]
> @acocac @pl-marasco can you please confirm that I can merge?

All is ok. The suggested changes affect mainly one of the notebooks within the example folder.

**Pull request merged**
